"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from spacetraders import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Agent:
    
    account_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('accountId') }})
    credits: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('credits') }})
    r"""The number of credits the agent has available. Credits can be negative if funds have been overdrawn."""
    headquarters: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('headquarters') }})
    r"""The headquarters of the agent."""
    starting_faction: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('startingFaction') }})
    r"""The faction the agent started with."""
    symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('symbol') }})
    