"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from spacetraders import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ContractDeliverGood:
    r"""The details of a delivery contract. Includes the type of good, units needed, and the destination."""
    destination_symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('destinationSymbol') }})
    r"""The destination where goods need to be delivered."""
    trade_symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('tradeSymbol') }})
    r"""The symbol of the trade good to deliver."""
    units_fulfilled: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('unitsFulfilled') }})
    r"""The number of units fulfilled on this contract."""
    units_required: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('unitsRequired') }})
    r"""The number of units that need to be delivered on this contract."""
    

