"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import factiontrait as shared_factiontrait
from dataclasses_json import Undefined, dataclass_json
from spacetraders import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class Faction:
    description: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('description') }})
    headquarters: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('headquarters') }})
    is_recruiting: bool = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('isRecruiting') }})
    r"""Whether or not the faction is currently recruiting new agents."""
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('symbol') }})
    traits: list[shared_factiontrait.FactionTrait] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('traits') }})
    

