"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from spacetraders import utils

class FactionTraitSymbol(str, Enum):
    r"""The unique identifier of the trait."""
    BUREAUCRATIC = 'BUREAUCRATIC'
    SECRETIVE = 'SECRETIVE'
    CAPITALISTIC = 'CAPITALISTIC'
    INDUSTRIOUS = 'INDUSTRIOUS'
    PEACEFUL = 'PEACEFUL'
    DISTRUSTFUL = 'DISTRUSTFUL'
    WELCOMING = 'WELCOMING'
    SMUGGLERS = 'SMUGGLERS'
    SCAVENGERS = 'SCAVENGERS'
    REBELLIOUS = 'REBELLIOUS'
    EXILES = 'EXILES'
    PIRATES = 'PIRATES'
    RAIDERS = 'RAIDERS'
    CLAN = 'CLAN'
    GUILD = 'GUILD'
    DOMINION = 'DOMINION'
    FRINGE = 'FRINGE'
    FORSAKEN = 'FORSAKEN'
    ISOLATED = 'ISOLATED'
    LOCALIZED = 'LOCALIZED'
    ESTABLISHED = 'ESTABLISHED'
    NOTABLE = 'NOTABLE'
    DOMINANT = 'DOMINANT'
    INESCAPABLE = 'INESCAPABLE'
    INNOVATIVE = 'INNOVATIVE'
    BOLD = 'BOLD'
    VISIONARY = 'VISIONARY'
    CURIOUS = 'CURIOUS'
    DARING = 'DARING'
    EXPLORATORY = 'EXPLORATORY'
    RESOURCEFUL = 'RESOURCEFUL'
    FLEXIBLE = 'FLEXIBLE'
    COOPERATIVE = 'COOPERATIVE'
    UNITED = 'UNITED'
    STRATEGIC = 'STRATEGIC'
    INTELLIGENT = 'INTELLIGENT'
    RESEARCH_FOCUSED = 'RESEARCH_FOCUSED'
    COLLABORATIVE = 'COLLABORATIVE'
    PROGRESSIVE = 'PROGRESSIVE'
    MILITARISTIC = 'MILITARISTIC'
    TECHNOLOGICALLY_ADVANCED = 'TECHNOLOGICALLY_ADVANCED'
    AGGRESSIVE = 'AGGRESSIVE'
    IMPERIALISTIC = 'IMPERIALISTIC'
    TREASURE_HUNTERS = 'TREASURE_HUNTERS'
    DEXTEROUS = 'DEXTEROUS'
    UNPREDICTABLE = 'UNPREDICTABLE'
    BRUTAL = 'BRUTAL'
    FLEETING = 'FLEETING'
    ADAPTABLE = 'ADAPTABLE'
    SELF_SUFFICIENT = 'SELF_SUFFICIENT'
    DEFENSIVE = 'DEFENSIVE'
    PROUD = 'PROUD'
    DIVERSE = 'DIVERSE'
    INDEPENDENT = 'INDEPENDENT'
    SELF_INTERESTED = 'SELF_INTERESTED'
    FRAGMENTED = 'FRAGMENTED'
    COMMERCIAL = 'COMMERCIAL'
    FREE_MARKETS = 'FREE_MARKETS'
    ENTREPRENEURIAL = 'ENTREPRENEURIAL'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class FactionTrait:
    
    description: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('description') }})
    r"""A description of the trait."""
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    r"""The name of the trait."""
    symbol: FactionTraitSymbol = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('symbol') }})
    r"""The unique identifier of the trait."""
    