"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import markettradegood as shared_markettradegood
from ..shared import markettransaction as shared_markettransaction
from ..shared import tradegood as shared_tradegood
from dataclasses_json import Undefined, dataclass_json
from spacetraders import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class Market:
    exchange: list[shared_tradegood.TradeGood] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('exchange') }})
    r"""The list of goods that are bought and sold between agents at this market."""
    exports: list[shared_tradegood.TradeGood] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('exports') }})
    r"""The list of goods that are exported from this market."""
    imports: list[shared_tradegood.TradeGood] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('imports') }})
    r"""The list of goods that are sought as imports in this market."""
    symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('symbol') }})
    r"""The symbol of the market. The symbol is the same as the waypoint where the market is located."""
    trade_goods: Optional[list[shared_markettradegood.MarketTradeGood]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('tradeGoods'), 'exclude': lambda f: f is None }})
    r"""The list of goods that are traded at this market. Visible only when a ship is present at the market."""
    transactions: Optional[list[shared_markettransaction.MarketTransaction]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('transactions'), 'exclude': lambda f: f is None }})
    r"""The list of recent transactions at this market. Visible only when a ship is present at the market."""
    

