"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import dateutil.parser
from dataclasses_json import Undefined, dataclass_json
from datetime import datetime
from enum import Enum
from marshmallow import fields
from spacetraders import utils

class MarketTransactionType(str, Enum):
    r"""The type of transaction."""
    PURCHASE = 'PURCHASE'
    SELL = 'SELL'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class MarketTransaction:
    
    price_per_unit: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('pricePerUnit') }})
    r"""The price per unit of the transaction."""
    ship_symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('shipSymbol') }})
    r"""The symbol of the ship that made the transaction."""
    timestamp: datetime = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('timestamp'), 'encoder': utils.datetimeisoformat(False), 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    r"""The timestamp of the transaction."""
    total_price: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('totalPrice') }})
    r"""The total price of the transaction."""
    trade_symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('tradeSymbol') }})
    r"""The symbol of the trade good."""
    type: MarketTransactionType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    r"""The type of transaction."""
    units: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('units') }})
    r"""The number of units of the transaction."""
    waypoint_symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('waypointSymbol') }})
    r"""The symbol of the waypoint where the transaction took place."""
    