"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import shipnav as shared_shipnav
from ..shared import shipregistration as shared_shipregistration
from dataclasses_json import Undefined, dataclass_json
from spacetraders import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ScannedShipEngine:
    r"""The engine of the ship."""
    
    symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('symbol') }})
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ScannedShipFrame:
    r"""The frame of the ship."""
    
    symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('symbol') }})
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ScannedShipMounts:
    r"""A mount on the ship."""
    
    symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('symbol') }})
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ScannedShipReactor:
    r"""The reactor of the ship."""
    
    symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('symbol') }})
    

@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ScannedShip:
    r"""The ship that was scanned. Details include information about the ship that could be detected by the scanner."""
    
    engine: ScannedShipEngine = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('engine') }})
    r"""The engine of the ship."""
    nav: shared_shipnav.ShipNav = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('nav') }})
    r"""The navigation information of the ship."""
    registration: shared_shipregistration.ShipRegistration = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('registration') }})
    r"""The public registration information of the ship"""
    symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('symbol') }})
    r"""The globally unique identifier of the ship."""
    frame: Optional[ScannedShipFrame] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('frame'), 'exclude': lambda f: f is None }})
    r"""The frame of the ship."""
    mounts: Optional[list[ScannedShipMounts]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('mounts'), 'exclude': lambda f: f is None }})
    reactor: Optional[ScannedShipReactor] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('reactor'), 'exclude': lambda f: f is None }})
    r"""The reactor of the ship."""
    