"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ShipNavFlightMode(str, Enum):
    r"""The ship's set speed when traveling between waypoints or systems."""
    DRIFT = 'DRIFT'
    STEALTH = 'STEALTH'
    CRUISE = 'CRUISE'
    BURN = 'BURN'
