"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import shiprequirements as shared_shiprequirements
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from spacetraders import utils
from typing import Optional

class ShipMountDeposits(str, Enum):
    QUARTZ_SAND = 'QUARTZ_SAND'
    SILICON_CRYSTALS = 'SILICON_CRYSTALS'
    PRECIOUS_STONES = 'PRECIOUS_STONES'
    ICE_WATER = 'ICE_WATER'
    AMMONIA_ICE = 'AMMONIA_ICE'
    IRON_ORE = 'IRON_ORE'
    COPPER_ORE = 'COPPER_ORE'
    SILVER_ORE = 'SILVER_ORE'
    ALUMINUM_ORE = 'ALUMINUM_ORE'
    GOLD_ORE = 'GOLD_ORE'
    PLATINUM_ORE = 'PLATINUM_ORE'
    DIAMONDS = 'DIAMONDS'
    URANITE_ORE = 'URANITE_ORE'
    MERITIUM_ORE = 'MERITIUM_ORE'

class ShipMountSymbol(str, Enum):
    MOUNT_GAS_SIPHON_I = 'MOUNT_GAS_SIPHON_I'
    MOUNT_GAS_SIPHON_II = 'MOUNT_GAS_SIPHON_II'
    MOUNT_GAS_SIPHON_III = 'MOUNT_GAS_SIPHON_III'
    MOUNT_SURVEYOR_I = 'MOUNT_SURVEYOR_I'
    MOUNT_SURVEYOR_II = 'MOUNT_SURVEYOR_II'
    MOUNT_SURVEYOR_III = 'MOUNT_SURVEYOR_III'
    MOUNT_SENSOR_ARRAY_I = 'MOUNT_SENSOR_ARRAY_I'
    MOUNT_SENSOR_ARRAY_II = 'MOUNT_SENSOR_ARRAY_II'
    MOUNT_SENSOR_ARRAY_III = 'MOUNT_SENSOR_ARRAY_III'
    MOUNT_MINING_LASER_I = 'MOUNT_MINING_LASER_I'
    MOUNT_MINING_LASER_II = 'MOUNT_MINING_LASER_II'
    MOUNT_MINING_LASER_III = 'MOUNT_MINING_LASER_III'
    MOUNT_LASER_CANNON_I = 'MOUNT_LASER_CANNON_I'
    MOUNT_MISSILE_LAUNCHER_I = 'MOUNT_MISSILE_LAUNCHER_I'
    MOUNT_TURRET_I = 'MOUNT_TURRET_I'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ShipMount:
    r"""A mount is installed on the exterier of a ship."""
    
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    requirements: shared_shiprequirements.ShipRequirements = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('requirements') }})
    r"""The requirements for installation on a ship"""
    symbol: ShipMountSymbol = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('symbol') }})
    deposits: Optional[list[ShipMountDeposits]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('deposits'), 'exclude': lambda f: f is None }})
    description: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('description'), 'exclude': lambda f: f is None }})
    strength: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('strength'), 'exclude': lambda f: f is None }})
    