"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import shipengine as shared_shipengine
from ..shared import shipframe as shared_shipframe
from ..shared import shipmodule as shared_shipmodule
from ..shared import shipmount as shared_shipmount
from ..shared import shipreactor as shared_shipreactor
from ..shared import shiptype as shared_shiptype
from dataclasses_json import Undefined, dataclass_json
from spacetraders import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ShipyardShip:
    
    description: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('description') }})
    engine: shared_shipengine.ShipEngine = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('engine') }})
    r"""The engine determines how quickly a ship travels between waypoints."""
    frame: shared_shipframe.ShipFrame = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('frame') }})
    r"""The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable."""
    modules: list[shared_shipmodule.ShipModule] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('modules') }})
    mounts: list[shared_shipmount.ShipMount] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('mounts') }})
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    purchase_price: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('purchasePrice') }})
    reactor: shared_shipreactor.ShipReactor = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('reactor') }})
    r"""The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons."""
    type: Optional[shared_shiptype.ShipType] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type'), 'exclude': lambda f: f is None }})
    