"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import shipcargo as shared_shipcargo
from ..shared import shipcrew as shared_shipcrew
from ..shared import shipengine as shared_shipengine
from ..shared import shipframe as shared_shipframe
from ..shared import shipfuel as shared_shipfuel
from ..shared import shipmodule as shared_shipmodule
from ..shared import shipmount as shared_shipmount
from ..shared import shipnav as shared_shipnav
from ..shared import shipreactor as shared_shipreactor
from ..shared import shipregistration as shared_shipregistration
from dataclasses_json import Undefined, dataclass_json
from spacetraders import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Ship:
    r"""A ship"""
    
    cargo: shared_shipcargo.ShipCargo = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cargo') }})
    crew: shared_shipcrew.ShipCrew = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('crew') }})
    r"""The ship's crew service and maintain the ship's systems and equipment."""
    engine: shared_shipengine.ShipEngine = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('engine') }})
    r"""The engine determines how quickly a ship travels between waypoints."""
    frame: shared_shipframe.ShipFrame = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('frame') }})
    r"""The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable."""
    fuel: shared_shipfuel.ShipFuel = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('fuel') }})
    r"""Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action."""
    modules: list[shared_shipmodule.ShipModule] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('modules') }})
    mounts: list[shared_shipmount.ShipMount] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('mounts') }})
    nav: shared_shipnav.ShipNav = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('nav') }})
    r"""The navigation information of the ship."""
    reactor: shared_shipreactor.ShipReactor = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('reactor') }})
    r"""The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons."""
    registration: shared_shipregistration.ShipRegistration = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('registration') }})
    r"""The public registration information of the ship"""
    symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('symbol') }})
    r"""The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]_[HEX_ID]`"""
    