"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import dateutil.parser
from ..shared import shipnavroutewaypoint as shared_shipnavroutewaypoint
from dataclasses_json import Undefined, dataclass_json
from datetime import datetime
from marshmallow import fields
from spacetraders import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ShipNavRoute:
    r"""The routing information for the ship's most recent transit or current location."""
    arrival: datetime = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('arrival'), 'encoder': utils.datetimeisoformat(False), 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    r"""The date time of the ship's arrival. If the ship is in-transit, this is the expected time of arrival."""
    departure: shared_shipnavroutewaypoint.ShipNavRouteWaypoint = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('departure') }})
    r"""The destination or departure of a ships nav route."""
    departure_time: datetime = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('departureTime'), 'encoder': utils.datetimeisoformat(False), 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    r"""The date time of the ship's departure."""
    destination: shared_shipnavroutewaypoint.ShipNavRouteWaypoint = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('destination') }})
    r"""The destination or departure of a ships nav route."""
    

