"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ShipRole(str, Enum):
    r"""The registered role of the ship"""
    FABRICATOR = 'FABRICATOR'
    HARVESTER = 'HARVESTER'
    HAULER = 'HAULER'
    INTERCEPTOR = 'INTERCEPTOR'
    EXCAVATOR = 'EXCAVATOR'
    TRANSPORT = 'TRANSPORT'
    REPAIR = 'REPAIR'
    SURVEYOR = 'SURVEYOR'
    COMMAND = 'COMMAND'
    CARRIER = 'CARRIER'
    PATROL = 'PATROL'
    SATELLITE = 'SATELLITE'
    EXPLORER = 'EXPLORER'
    REFINERY = 'REFINERY'
