"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import shipcargoitem as shared_shipcargoitem
from dataclasses_json import Undefined, dataclass_json
from spacetraders import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ShipCargo:
    capacity: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('capacity') }})
    r"""The max number of items that can be stored in the cargo hold."""
    inventory: list[shared_shipcargoitem.ShipCargoItem] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('inventory') }})
    r"""The items currently in the cargo hold."""
    units: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('units') }})
    r"""The number of items currently stored in the cargo hold."""
    

