"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ShipNavStatus(str, Enum):
    r"""The current status of the ship"""
    IN_TRANSIT = 'IN_TRANSIT'
    IN_ORBIT = 'IN_ORBIT'
    DOCKED = 'DOCKED'
