"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import shipnavflightmode as shared_shipnavflightmode
from ..shared import shipnavroute as shared_shipnavroute
from ..shared import shipnavstatus as shared_shipnavstatus
from dataclasses_json import Undefined, dataclass_json
from spacetraders import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ShipNav:
    r"""The navigation information of the ship."""
    
    flight_mode: shared_shipnavflightmode.ShipNavFlightMode = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('flightMode') }})
    r"""The ship's set speed when traveling between waypoints or systems."""
    route: shared_shipnavroute.ShipNavRoute = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('route') }})
    r"""The routing information for the ship's most recent transit or current location."""
    status: shared_shipnavstatus.ShipNavStatus = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status') }})
    r"""The current status of the ship"""
    system_symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('systemSymbol') }})
    r"""The system symbol of the ship's current location."""
    waypoint_symbol: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('waypointSymbol') }})
    r"""The waypoint symbol of the ship's current location, or if the ship is in-transit, the waypoint symbol of the ship's destination."""
    