"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from spacetraders import utils

class ShipCrewRotation(str, Enum):
    r"""The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale."""
    STRICT = 'STRICT'
    RELAXED = 'RELAXED'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ShipCrew:
    r"""The ship's crew service and maintain the ship's systems and equipment."""
    capacity: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('capacity') }})
    r"""The maximum number of crew members the ship can support."""
    current: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('current') }})
    r"""The current number of crew members on the ship."""
    morale: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('morale') }})
    r"""A rough measure of the crew's morale. A higher morale means the crew is happier and more productive. A lower morale means the ship is more prone to accidents."""
    required: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('required') }})
    r"""The minimum number of crew members required to maintain the ship."""
    rotation: ShipCrewRotation = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('rotation') }})
    r"""The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale."""
    wages: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('wages') }})
    r"""The amount of credits per crew member paid per hour. Wages are paid when a ship docks at a civilized waypoint."""
    

