"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class SystemType(str, Enum):
    r"""The type of waypoint."""
    NEUTRON_STAR = 'NEUTRON_STAR'
    RED_STAR = 'RED_STAR'
    ORANGE_STAR = 'ORANGE_STAR'
    BLUE_STAR = 'BLUE_STAR'
    YOUNG_STAR = 'YOUNG_STAR'
    WHITE_DWARF = 'WHITE_DWARF'
    BLACK_HOLE = 'BLACK_HOLE'
    HYPERGIANT = 'HYPERGIANT'
    NEBULA = 'NEBULA'
    UNSTABLE = 'UNSTABLE'
