"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import shipnav as shared_shipnav
from dataclasses_json import Undefined, dataclass_json
from spacetraders import utils
from typing import Optional



@dataclasses.dataclass
class GetShipNavSecurity:
    agent_token: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    




@dataclasses.dataclass
class GetShipNavRequest:
    ship_symbol: str = dataclasses.field(metadata={'path_param': { 'field_name': 'shipSymbol', 'style': 'simple', 'explode': False }})
    r"""The ship symbol"""
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class GetShipNav200ApplicationJSON:
    r"""The current nav status of the ship."""
    data: shared_shipnav.ShipNav = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    r"""The navigation information of the ship."""
    




@dataclasses.dataclass
class GetShipNavResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    get_ship_nav_200_application_json_object: Optional[GetShipNav200ApplicationJSON] = dataclasses.field(default=None)
    r"""The current nav status of the ship."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

