"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import shipnav as shared_shipnav
from dataclasses_json import Undefined, dataclass_json
from spacetraders import utils
from typing import Optional



@dataclasses.dataclass
class OrbitShipSecurity:
    agent_token: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    




@dataclasses.dataclass
class OrbitShipRequest:
    ship_symbol: str = dataclasses.field(metadata={'path_param': { 'field_name': 'shipSymbol', 'style': 'simple', 'explode': False }})
    r"""The symbol of the ship"""
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class OrbitShipOrbitShip200ResponseData:
    nav: shared_shipnav.ShipNav = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('nav') }})
    r"""The navigation information of the ship."""
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class OrbitShipOrbitShip200Response:
    r"""The ship has successfully moved into orbit at it's current location."""
    data: OrbitShipOrbitShip200ResponseData = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    




@dataclasses.dataclass
class OrbitShipResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    orbit_ship_200_response: Optional[OrbitShipOrbitShip200Response] = dataclasses.field(default=None)
    r"""The ship has successfully moved into orbit at it's current location."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

