"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import agent as shared_agent
from ..shared import markettransaction as shared_markettransaction
from ..shared import shipfuel as shared_shipfuel
from dataclasses_json import Undefined, dataclass_json
from spacetraders import utils
from typing import Optional



@dataclasses.dataclass
class RefuelShipSecurity:
    agent_token: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    




@dataclasses.dataclass
class RefuelShipRequest:
    ship_symbol: str = dataclasses.field(metadata={'path_param': { 'field_name': 'shipSymbol', 'style': 'simple', 'explode': False }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class RefuelShip200ApplicationJSONData:
    agent: shared_agent.Agent = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('agent') }})
    fuel: shared_shipfuel.ShipFuel = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('fuel') }})
    r"""Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action."""
    transaction: shared_markettransaction.MarketTransaction = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('transaction') }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class RefuelShip200ApplicationJSON:
    r"""OK"""
    data: RefuelShip200ApplicationJSONData = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data') }})
    




@dataclasses.dataclass
class RefuelShipResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    refuel_ship_200_application_json_object: Optional[RefuelShip200ApplicationJSON] = dataclasses.field(default=None)
    r"""OK"""
    

